// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD23hLpocr7nOk4vGQSaRVQ8bVaocYW3W4',
    appId: '1:784939506601:web:4785aa059b81a1a34242b8',
    messagingSenderId: '784939506601',
    projectId: 'flutter-firebase-session-a6270',
    authDomain: 'flutter-firebase-session-a6270.firebaseapp.com',
    storageBucket: 'flutter-firebase-session-a6270.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUQgaJS3eEU7cFY3eKF92j72r0rrSAwKY',
    appId: '1:784939506601:android:911e3e8a0bd9c1ef4242b8',
    messagingSenderId: '784939506601',
    projectId: 'flutter-firebase-session-a6270',
    storageBucket: 'flutter-firebase-session-a6270.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg5ilp_mWTrkja7d4E7bw3y5Sl6BtIVP4',
    appId: '1:784939506601:ios:c7c14bbc7ef932ea4242b8',
    messagingSenderId: '784939506601',
    projectId: 'flutter-firebase-session-a6270',
    storageBucket: 'flutter-firebase-session-a6270.firebasestorage.app',
    iosBundleId: 'com.example.app1',
  );
}
